import { useState, useCallback } from "react"



export default useLocation = (initial) => {
        var arr = []
        
        arr.push({"title": "Andhra Pradesh Tourism" ,
                "tagline": "The 29th state of India" ,
                "desc": "\n Blessed with two beautiful rivers, Krishna and Godavari, Andhra Pradesh has the Bay of Bengal to its west, and it boasts of a coastline of 972km, the longest in the country. This state is widely advertised as the Kohinoor of India by the tourism department. The state is most visited for its world famous Tirupati temple. Srisailam Mallikarjuneswar temple is another famous Shiva shrine and is one of the 12 Jyotirlinga temples in India.\n\n In spite of the recent division of the state of Andhra Pradesh, which resulted in the formation Seemandhra which is what was left of Andhra Pradesh after Telangana region was carved out, Seemandhra seems to have got the better share regarding tourism. Places like Belum caves, Nagarjuna Konda, Borra caves and Pulicat Lake have all come under Seemandhra. Apart from this, it retains the better part of the culture and cuisine of Andhra Pradesh and has an already established tourism development. The state is home to various centres that have quite a lot of Buddhist influence like Dhulikatta, Bavikonda, Thotlakonda, Amravati, Nagarjuna Konda, etc. The Vijayanagara dynasty can be credited for constructing some breathtaking structures in the state like Srisailam and Lepakshi temples. One of the famous mosques in the state is the Shahi Jamia Masjid in Adoni of Kurnool district. Rajahmundry city, located on the banks of Godavari River is one of the main attractions of the city. Likewise, Kolleru Lake is one of the largest freshwater lakes in India located in the state of Andhra Pradesh. A trip to this state will leave you completely mesmerised. \nRead More\n" ,
                "img": "https://www.holidify.com/images/bgImages/ANDHRA-PRADESH.jpg"})
        arr.push({"title": "Assam Tourism" ,
                "tagline": "The Gateway to North-East India" ,
                "desc": "\n Assam, a treasure trove of natural beauty and diverse history, is one of the least explored regions in the country, lending it an immaculate, untouched aura that is sure to allure you. A land of wild forests, mighty rivers, and acres and acres of tea plantations, Assam, located in North East India, has a breath-taking landscape and is known to be one of the top biodiversity hotspots in the entire world. A veritable paradise, Assam shares international borders with both Bangladesh and Bhutan and boasts of its vibrant culture and scenic beauty, as well as its historical significance. One of the most beautiful states of India, Assam is the gateway to the enchanting and unexploited northeastern part of the country. With the majestic Brahmaputra river, magnificent hills, its rich flora and fauna, the state is every tourist's paradise. \n\n Spread over an area of 1250 kilometres, Majuli is the largest river island of Asia and is famous for its traditions and its vibrant culture. Home to the 'Mising' or 'Mishing' tribe, Majuli is a great place to sit back and take in the beauty of the village which is surrounded by water. The Misings have a unique lifestyle, and they celebrate various festivals with a lot of pomp and show. Dibrugarh, a city in Assam,  is known as the Tea City of India. Hajo, an extremely ancient pilgrimage centre for not one or two, but three different religions, stands as a beautiful example of the secular diversity that exists in India. The area is dotted with numerous temples, mosques and churches, as well as other religious and sacred artefacts. Haflong, Assam?s only hill station, is a stunningly beautiful place, marked with rolling mountains and lush green valleys. It is also known as 'The Land of the Blue Hills'.\nRead More\n" ,
                "img": "https://www.holidify.com/images/bgImages/ASSAM.jpg"})
        arr.push({"title": "Arunachal Pradesh Tourism" ,
                "tagline": "Land of the dawn-lit mountains" ,
                "desc": "\n Home to picturesque mountains, unexplored passes, tranquil lakes and famous monasteries, Arunachal Pradesh is an amazing destination for an amazing holiday. Arunachal Pradesh is the perfect state for you if you wish to explore the tribal culture and the simplicity of their exquisite beauty. Its amazing array of flora and fauna, in a unique habitat with glaciers, high altitude meadows and sub-tropical forests add to the charm of the beautiful state.\n\n Arunachal Pradesh, bordered on the south by Assam, on the west by Bhutan, on the north and northeast by China, and on the east by Myanmar is also known as the \"Orchid State of India\" or the \"Paradise of the Botanists\". More than 500 species of birds have been recorded to be found in this state, many of which are highly endangered and restricted to this state. For the most part, Arunachal Pradesh is covered with serene mountains that offer one a breathtaking view during the winters. As the snow covers the peaks of these mountains, flora and fauna display a state of calmness and freshness in the region. The crafty, yet traditional people of the state welcome one and all with a smile on their faces and love and warmth in their hearts.\nRead More\n" ,
                "img": "https://www.holidify.com/images/bgImages/ARUNACHAL-PRADESH.jpg"})
        arr.push({"title": "Bihar Tourism" ,
                "tagline": "Blissful Bihar" ,
                "desc": "\n The land where the Buddha once lived, a land of monasteries - Bihar is visited by a considerable number of Buddhist followers as well as tourists of other faiths all through the year. Its association with Buddhism and Jainism makes it a must visit place for peace seekers, people who would like to get a feel of the tribal culture and experience life in the rural parts of India, and those who would like to get a glimpse of our glorious past.\n\n Derived from the Sanskrit word 'Vihara', which means monastery, Bihar has a glorious heritage in the context of Indian history. Bihar is located in the eastern parts of India situated in the Gangetic plains, and it shares its borders with Uttar Pradesh in the West, Jharkhand in the South, West Bengal in the east, and Nepal in the North. The spiritual importance of Bihar comes from the fact that it is the place where the Buddha once lived and attained Nirvana. His footsteps can be traced through his teachings and the monuments which stand tall to this day, serving to guide people and show them the rightpath.Bihar is a blessed land as it was here under a Bodhi Tree that Prince Siddhartha meditated to attain enlightenment and came to be known as the Buddha. Bihar is a famous destination not just for Buddhists but also for Jains and Hindus. It is the amalgamation of religion, spirituality, history and education which makes the state one of its kind. While every city of Bihar has something to offer some of the major attractions are Bodh Gaya, Rajgir, Patna, Vaishali, Pawapuri and Nalanda.\nRead More\n" ,
                "img": "https://www.holidify.com/images/bgImages/BIHAR.jpg"})
        arr.push({"title": "Goa" ,
                "tagline": "Beaches, Sunsets and Crazy Nights" ,
                "desc": "\n Lying on the western coast, Goa is India's smallest state and unlike any other, known for its endless beaches, stellar nightlife, eclectic seafood, world-heritage listed architecture. Spread across just 3,702 km, Goa lies in the Konkan region. It is a far cry from the hippie haven or a beach getaway, and one of the only few destinations that is open 24x7. The laid-backness (susegad) of Goa attracts as many international tourists as it does Indians, or even more so.\n\n The Goans are quite friendly towards tourists and celebrate many festivals throughout the year, the most famous being the New Year and Goa Carnival. While the seafood is excellent, Goa has one of the best nightlife in India with trendy bars, beach shacks, elegant cafes and many clubs and discotheques. Thanks to lower alcohol prices in the state, Goa is also great for younger tourists with relatively tighter pockets.For those of us perpetually confused between North Goa and South Goa, this might help - the state of Goa is divided into North Goa and South Goa. While North Goa is the nightlife hub where all the touristy beaches, flea markets, and beach shacks are located, South Goa is the land of luxurious resorts and laid-back beach vibes. Having been a Portuguese territory for almost 450 years, the Portuguese architecture is nowhere as prevalent as in Goa - visit one of the many whitewashed churches, crumbling forts or spectacular churches. The yellow houses with purple doors, ochre coloured mansions and oyester shell windows is what completes the kalieodscope of Goan architecture. Panjim, the capital city located in the centre overlooks the calm Mandovi River where the famous floating casinos of Goa are docked. The centre is well-connected with an international airport and roads and trains run from North to South part of Goa. With a coastline stretching for over 100 kilometres, Goa has stunning beaches. While Baga and Calangute are more popular among the Indian family crowd, Anjuna and Arambol draw a lot of foreign tourists. The beaches in South Goa are relatively lesser explored, but some of them like Agonda and Palolem are more beautiful." ,
                "img": "https://www.holidify.com/images/bgImages/GOA.jpg"})
        arr.push({"title": "Gujarat Tourism" ,
                "tagline": "Vibrant Gujarat" ,
                "desc": "\n Located in the westernmost part of India, Gujarat is home to several architectural marvels and is famous for its vibrant culture and rich heritage, apart from the scenic landscapes and mouth-watering cuisine. Offering a broad range of the most spectacular attractions, Gujarat, also known as 'The Land of Legends', presents a perfect blend of art, history, music and culture.\n\n Being the sole home of the pure Asiatic Lions, Gujarat also offers splendid views of the scenic beauty ranging from the Great Rann of Kutch to the hills of Satpura. Apart from the picturesque landscapes and the more than 1600 kilometres long coastline, Gujarat also offers its tourists with some magnificent ancient cave paintings, historic murals, holy temples, historic capitals, wildlife sanctuaries, beaches, hill resorts and fascinating handicrafts. Gujarat is a dry state but the cultural exuberance of the Gujratis will give rejuvenate you.\nRead More\n" ,
                "img": "https://www.holidify.com/images/bgImages/GUJARAT.jpg"})
        arr.push({"title": "Jammu and Kashmir Tourism" ,
                "tagline": "Paradise on the Earth" ,
                "desc": "\n Popularly known as the \"Paradise on Earth\", Jammu and Kashmir is world famous for its scenic splendour, snow-capped mountains, plentiful wildlife, exquisite monuments, hospitable people and local handicrafts.\u00a0Your trip to Jammu and Kashmir will be a memorable one as the state will not only appeal to you with its scenic beauty and snow-covered mountain ranges, but the adventure sports will take you to a different world.\u00a0\n\n Nestled in the Himalayan, Pir Panjal and Karakoram mountain ranges are renowned for their natural beauty and gentle people. Jammu and Kashmir is dotted with the most beautiful mountain peaks, massive glaciers, splendid monasteries, blue lakes, rivers, forests, verdant meadows and tall pine trees. While sports like Skiing, golf, trekking, river rafting, paragliding, camping make the trip to Jammu and Kashmir more adventurous, Amarnath and Vaishno Devi attract a large number of pilgrims every year. Dal Lake, Kashmir Valley, Khardung La Pass, Gulmarg, Shalimar Bagh are some of the major attractions of the state. The unparalleled beauty and charm of the state and the sweetness of the residents will remain etched in your memory forever.\nRead More\n" ,
                "img": "https://www.holidify.com/images/bgImages/JAMMU-AND-KASHMIR.jpg"})
        arr.push({"title": "Jharkhand Tourism" ,
                "tagline": "A New Experience" ,
                "desc": "\n One of the best places to visit for wildlife aficionados and nature lovers, Jharkhand is a state replete with a vast bounty of towering mountains, dense forests and gushing waterfalls. Blessed with a plethora of natural scenic vistas, Jharkhand is the place for you be if you are on the lookout for a one-on-one rendezvous with unperturbed, untouched nature. There is more to Jharkhand than just its scenic landscapes though, with several museums, temples and wildlife reserves scattered around the state. Formerly a part of Bihar, Jharkhand was carved out as a separate state almost two decades ago, thus creating the base for a glorious history, diverse culture and tribal simplicity that the state can now call it's very own.\n\n Jharkhand is 'the land of forests' as its name suggests and the state is famous for its rich variety of flora and fauna. The scenic beauty of forests, hills and plateaus from the Lodh Falls leaves an enchanting impression on tourists while the lush green forests that surround the state keeps it green and clean. Nature is considered as a vital and essential part of the life of tribal people who dominate the state, and this is one of the reasons that you can have a panoramic view of nature and its beauty. Ranchi Hills, Daasam Falls, Sun Temple, Baidyanath Dham are some of the major tourist attractions in Jharkhand.\nRead More\n" ,
                "img": "https://www.holidify.com/images/bgImages/JHARKHAND.jpg"})
        arr.push({"title": "West Bengal Tourism" ,
                "tagline": "Beautiful Bengal" ,
                "desc": "\n West Bengal boasts of different ethnicities, cultures, religions, people and languages which add to its beautiful landscapes, forests, coastal beauty as well as its heritage.\n\n The beautiful state of West Bengal attracts a significant number of tourists every year as the state is jewelled with mesmerising landscapes, snow-clad mountains, gushing sea, blossoming tea gardens, enormous deltas, lush green forests, plentiful wildlife, ancient temples and magnificent British monuments. The Tiger Hill, the Howrah Bridge, the Tea Gardens are some of the famous tourist spots which offer an insight into the vast culture and history of the West Bengal. The culture of the state is adorned by colourful fairs and festivals every month. A vast number of famous pilgrimages also attract a large number of tourists of all faiths and beliefs.\nRead More\n" ,
                "img": "https://www.holidify.com/images/bgImages/WEST-BENGAL.jpg"})
        arr.push({"title": "Karnataka Tourism" ,
                "tagline": "One State, Many Worlds" ,
                "desc": "\n Ranked the 4th most popular tourist state in the country, Karnataka has a bouquet of attractions to offer you. Expanded from Belgaum in the North to Bangalore in the south, it has something to offer to everybody; from beautiful landscapes to rich cultural heritage, serene beaches and scrumptious food, Karnataka is indeed a world in itself!\u00a0The Malayalis, the Tamilians, Konkanis, Kannadigas, even the Muslims and Christians have made Karnataka their home.\n\n It has the second highest number of protected monuments in India, Hampi being one which houses the maximum of them, was the capital of Vijayanagar Empire.\u00a0The world's largest monolith structure, the statue of Lord Gomteshwar in Shravanabelagola sees tens of thousands of pilgrims during Mahamastakabhisheka festival every 12 years.\u00a0Apart from history, Karnataka is also rich in nature's bounty and wildlife. It has 5 National Parks and over 25 wildlife sanctuaries of which Bandipur and Nagarhole national parks are most famous. Bengaluru, the capital of the state and the \"Silicon Valley of India\" is known as the city of startups and IT companies and attracts thousands of tourists every year. Coorg is one of the top destinations in Karnataka for its coffee plantations. Mysore, famous for the Mysore Palace, Hampi, famous for the ruins of Vijayanagara Empire and Chikmagalur, a hill station in the Malnad region of Karnataka are a few other popular places among the tourists.\nRead More\n" ,
                "img": "https://www.holidify.com/images/bgImages/KARNATAKA.jpg"})
        arr.push({"title": "Kerala Tourism" ,
                "tagline": "God's Own Country" ,
                "desc": "\n Famously known as 'God's Own Country', Kerala is a state located on the Malabar coast of Southern India. Home to a vast network of brackish lagoons called backwaters, ayurvedic massages, wildlife sanctuaries, sprawling tea gardens, hill-stations, palm tree-lined beaches and colourful dance forms, Kerala has everything on offer to take your pick from!\n\n \n" ,
                "img": "https://www.holidify.com/images/bgImages/KERALA.jpg"})
        arr.push({"title": "Madhya Pradesh Tourism" ,
                "tagline": "The Heart of Incredible India" ,
                "desc": "\n Madhya Pradesh got its name because of its geographical position, being located in the centre of India. However, it's tagline 'The Heart of Incredible India' has more to do with the fact that it houses facets of the whole of India into this state. From the historical monuments to modern amenities, culture, food and people- this state gives a taste of entire India packed within its geographical boundaries.\n\n Madhya Pradesh is one of the few states that is surrounded by other states on all its sides. It lies in the plain regions of the country and occupies one of the oldest parts of the Indian Subcontinent which was once the land of the Gonds called the Gondwana. Every twelve years the grand fair of Kumbh Mela is organised here. Madhya Pradesh has some spectacular historical places in its region, of which a temple made of glass in Indore is quite famous.\u00a0Ujjain, a sacred city for the Hindus, is a renowned place in the world as it is one of 12 Jyotirlingas in India. Madhya Pradesh is particularly famous for its Khajuraho temples which exhibit the erotic sculptures depicting the ancient India Kama Sutra text. The great Sanchi Stupa constructed during King Ashoka's reign is situated here in Bhopal. The Bandhavgarh National Park which houses the Barasingha and the Tigers reserve is also located here.\nRead More\n" ,
                "img": "https://www.holidify.com/images/bgImages/MADHYA-PRADESH.jpg"})
        arr.push({"title": "Maharashtra Tourism" ,
                "tagline": "Gateway to the heart of India" ,
                "desc": "\n Often called the 'Gateway to the Heart of India', Maharashtra is the third largest state and second most populous state than in the country. Owing to its proximity to the Western Ghats, it is blessed with a picturesque backdrop of the mountains on one side and has the beautiful Konkan coastal belt on the other.\n\n Maharashtra, the land of everything unlimited invites you into its widespread plethora of attractions. It is adorned by the beautiful Sahyadri ranges of the Western Ghats with high mountains that disappear into the morning mist, while the sprawling belt of the Konkan Coast mesmerises the eyes by its white beaches. The ruins of the ancient forts and palaces in Pune and Ratnagiri among others proudly narrates the story of the then mighty rulers of Maharashtra. Centuries-old temples situated in places like Pandharpur, Ozar are still rooted in their traditions, offering sanctuary to pilgrims. As do the small hill stations of Mahabaleshwar, Lonavala, Matheran, nestled cosily in nature, provide respite to travellers from the hustle and bustle of the cities. People of diverse culture and religion live amicably in this state, which is why there is much ado about the culture of Maharashtra which while retaining its original Marathi culture has beautifully embraced other cultures that have come to call this state their home. Apart from being rich in history, traditional arts and lifestyle, it is also famous for its economy primarily because Mumbai -the financial capital of India is situated here. The entertainment hub - the Bollywood film industry also finds its origin in this state. The amalgamation of these varieties of things that this state offers will make your visit here absolutely worthwhile.\nRead More\n" ,
                "img": "https://www.holidify.com/images/bgImages/MAHARASHTRA-GOA.jpg"})
        arr.push({"title": "Manipur Tourism" ,
                "tagline": "Jewel of India" ,
                "desc": "\n The jewel city of India, Manipur in the north-eastern part of the country, is listed among one of the most beautiful places of India where Mother Nature has been extra generous in her bounty. Least touched and least discovered, Manipur promises to be a great tourist discovery as the state offers endless enjoyment and pleasure with its exotic landscape, undulating hills, green valleys, blue lakes and dense forests. The Keibul Lamjao National Park in Manipur is the only floating national park in the world. Manipur is well-known in the whole country for its Rasleelas and Manipuri, which is the classical dance of the state.\n\n Richly endowed with the natural beauty of waterfalls, lakes, streams, evergreen forests surrounded by nine sub-Himalayan ranges that attract tourists from all over the world, Manipur is beautiful, calm and serene with it's most ecstatic simplicity. Its greenery combined with the pleasant climate makes it attractive to tourists.\u00a0Loktak Lake, Sendra Island, INA Memorial, Keibul Lamjao National Park are some of the major tourist attractions in the state. Shopping in Manipur is all about local handicraft, handloom and jewellery which are all readily available at the Khwairamband Bazar, Tribal Emporium and Sangai Handloom and Handloom House apart from the colourful local shops in the various cities.\nRead More\n" ,
                "img": "https://www.holidify.com/images/bgImages/MANIPUR.jpg"})
        arr.push({"title": "Meghalaya Tourism" ,
                "tagline": "The abode of clouds" ,
                "desc": "\n Meghalaya, the abode of clouds, is one of the most beautiful states in North-East India offering a variety of sights, activities, food and festivals to the tourists. Well known for Cherapunjji, the place which receives one of the maximum rainfall in the world, Meghalaya can mesmerise you with its hills, valleys, lakes, caves and waterfalls which when combined with the beautiful clouds, give it a very serene, beautiful look.\n\n Shillong is the capital of Meghalaya, and it?s the most urbanised area you will see in the entire state. Shillong has a lot of leftover British colonial influence that is evident from the plentiful British architecture. Owing to the magnificent lakes all around the town, and the hills surrounding it, Shillong has often been called the Scotland of the East.\u00a0Cherrapunji is famous for its rainfall, and it used to be the wettest place on Earth before the title was taken over by Mawsynram, which is less than 100 kilometres away from Cherrapunji. The Living Double-decker Root Bridge is a famous attraction in Cherrapunji, where trekking and hiking activities are offered for tourists.If you want to take a look at Asia?s cleanest village, don?t forget to visit Mawlynnong. Lying on the border separating India from Bangladesh, Mawlynnong is an amazingly clean village in Meghalaya where every street corner has a bamboo dustbin to ensure nature-friendly disposal of trash. The focal point of attraction of this village is the Sky Watch, which is a bamboo structure that offers sweeping views of the Bangladeshi plains from the top. Meghalaya has a history of rich craftsmanship, and wood-carving and artistic weaving are famous crafts here, especially in the Jaintia and Khasi districts.\u00a0\nRead More\n" ,
                "img": "https://www.holidify.com/images/bgImages/MEGHALAYA.jpg"})
        arr.push({"title": "Mizoram Tourism" ,
                "tagline": "Where nature's spirit dwells" ,
                "desc": "\n Known as the 'Songbird of India', the northeastern state of Mizoram is one of the smallest states in India. The moderate climate of Mizoram, which is comfortable even in during summer makes it an attractive destination for all the tourists. The vast culture and grand festivals of the state have a unique, irresistible charm which can not be explained or read; it can only be felt once you are in the peaceful, serene land of Mizoram. The dense greenery and the 21 hill ranges that stretch throughout the territory of Mizoram is sure to take you surrounded to a different world. An Inner Line Pass is required to enter Mizoram.\u00a0\n\n Mizoram offers you a calm, serene atmosphere with exciting outdoor activities in the beautiful lush green surroundings which keeps you close to the peaceful nature. With grand festivals, happy people wearing colourful traditional costumes, Mizoram welcomes you to explore its beauty and richness. Don't forget to stop by the tribal artisans and get amazed by their unique talent and pick a traditional shawl for yourself as a souvenir. For non-vegetarian people, the food of the state will be a real treat while vegetarians will have to choose carefully from the dishes. If you love to be in nature's arms, then Mizoram is the place for you!\u00a0Indians need an Inner Line Permit (ILP) to enter the state. The cost is INR 170 for a 15-day permit. The process to get an extension is slightly difficult. One can get an ILP documentation done at the Lengpui Airport in Aizwal.\nRead More\n" ,
                "img": "https://www.holidify.com/images/bgImages/MIZORAM.jpg"})
        arr.push({"title": "Nagaland Tourism" ,
                "tagline": "Gateway to the heart of India" ,
                "desc": "\n Nicknamed as the ?Land of Festivals?, Nagaland is a quaint state in the north-east part of the country and is one of the most-loved hill station tourist destinations in India. Nagaland is as much about scenic beauty as it is about carefully preserved history and tradition, and a visit to this mesmerising state will open up a vista of things you can see and do to make your holiday a memorable one. Inhabited by the tribes who are very protective towards their culture and identity, Nagaland is another name for beauty and bounty. Colourful costumes, spicy cuisines, pleasant weather, traditional villages, beautiful dance forms and lyrical songs are all that define the north-eastern state of Nagaland.\n\n Nagaland has many places to offer to nature lovers; Japfu Peak, Dzukou Valley, Shilloi Lake are some of the places where people can find nature in its bounty. Like the other north-eastern states, Nagaland is also rich in culture with a variety of tribes.\u00a0As all the tribes have their festivals and ceremonies, Nagaland is always ready to welcome a festival with great joy, and gaiety and food remain as much a part of the celebration as the dances and songs. Naga people eat almost anything that they can lay their hands on, be it dog, pork, snails or even an elephant and no part of the animal is wasted be it the skin or intestine. It shows how much they relish food and drinks. These jolly, colourful and crafty people are the soul of the state while nature attracts tourists from all over the world.\nRead More\n" ,
                "img": "https://www.holidify.com/images/bgImages/NAGALAND.jpg"})
        arr.push({"title": "Odisha Tourism" ,
                "tagline": "The Soul of Incredible India" ,
                "desc": "\n Odisha- the land of paddy fields and palm-fringed silver beaches, temples, rivers, waterfalls and tribal people, is filled with major attractions such as the temples of Bhubaneshwar and Puri, miles of clean beaches and the magnificent Sun Temple of Konark.\n\n Odisha, the state with a glorious history, is filled with nature and adventure. Inhabited by tribal people, the not-so-developed state of Odisha must be visited to have the experience of the myriad wonders it has in store for everybody. Also known as the soul of India, Odisha is a place where you can relax on the beaches, visit the famous temples and explore the beauty and bounty of nature and wildlife. You can also find various monuments which gloriously stand to remind you of the history of the land. Odisha's art and culture, fairs and festivals, dances and music are a treat for the tourists who love to see colours and wish to enjoy life to the fullest. Visit the soul state of India and come back with a bag full of memories that will remain etched in your mind for a long time.\nRead More\n" ,
                "img": "https://www.holidify.com/images/bgImages/ODISHA.jpg"})
        arr.push({"title": "Punjab Tourism" ,
                "tagline": "Smiling State Of India" ,
                "desc": "\n Located in the northwestern part of India, Punjab means the land of five rivers. Known for its cuisine, culture and history, Punjab is visited by tourists who want to enjoy its vibrant culture and food.\n\n The fertile land of farms and forts, Punjab has been aptly nicknamed the 'Smiling Soul of India' where you will always see smiles on the faces of the inhabitants who take pride in their religion and culture. Though the state does not have any significant adventure activity to offer, yet entertainment is guaranteed!\u00a0There are many Forts in the state that tell the tale of the land's past. The Golden Temple, The Wagah border, The Jallianwala Bagh, The Sheesh Mahal are some of the major tourist attractions in Punjab. The list becomes endless as every street of Punjab is an attraction in itself; each region of Punjab has a different story and unique beauty hidden inside it.\nRead More\n" ,
                "img": "https://www.holidify.com/images/bgImages/PUNJAB.jpg"})
        arr.push({"title": "Rajasthan Tourism" ,
                "tagline": "The Incredible State of India" ,
                "desc": "\n The Indian state of Rajasthan is popularly known to many as the Land of the Kings, is a beautiful example of India?s age-old opulence and grandeur, traces of which still linger in the air of this state. One of the most colourful and vibrant states in the country, with a strong blend of culture, history, music, cuisine falling in love with Rajasthan doesn't take much time. Rajasthan has more history than the entire country put together- it is the realm of erstwhile Maharajas and their lavish palaces and majestic forts. Golden-sand deserts, traditional handicrafts, authentic cuisine and awe-inspiring palaces all contribute to making Rajasthan an ideal vacation spot. Don't forget to wish everyone with \"Khamma Ghani\" while you're here!\n\n Rajasthan abounds in forts which offer sweeping views of the panoramic landscape. Three most essential forts in Rajasthan are the Amber Fort in Jaipur, Mehrangarh Fort in Jodhpur and Jaisalmer Fort, commonly known as Sonar Quila. Rajasthan also has a significant number of palaces that are of historical significance, the famous ones being the Umaid Bhawan Palace and the Jaipur City Palace. Both of these palaces date back to the high times, and you can see the furniture and other objects used by the royal families on view in these palaces.\nRead More\n" ,
                "img": "https://www.holidify.com/images/bgImages/RAJASTHAN.jpg"})
        arr.push({"title": "Sikkim Tourism" ,
                "tagline": "Home to the Kanchenjunga" ,
                "desc": "\n Sikkim, located in the north-eastern region is the smallest state in India. Travelling across this Himalayan state is particularly highlighted by the dramatic contouring of the scenery from thick woodlands to colourful meadows to few barren patches to the panoramic views of the snowcapped mountains. Occupied by warm-hearted people offering some of the best hospitality and boasting of magnificent treks, snow activities and scenic views, Sikkim is truly a destination people fall in love with!\n\n The third highest peak in the world and jewel of the state, Kanchenjunga is visible from almost anywhere you stand. Characterised by freezing winters and cool summers, the state plays host to a large number of tourists all year round. Accessible mainly via road from the neighbouring states, the newly inaugurated Pakyong airport near the capital city of Gangtok highlights government efforts towards better connectivity. Until 1975, when it was merged with India, Sikkim functioned as an autonomous kingdom with its own monarchy. Since then, it has become an integral part of India with a distinctive culture which has evolved into a multifaceted one. Influenced by the peaceful coexistence of the dominant Nepalese community with the native Bhutias and the immigrant Lepchas, one will find many monasteries and Hindu shrines close to each other.\nRead More\n" ,
                "img": "https://www.holidify.com/images/bgImages/SIKKIM.jpg"})
        arr.push({"title": "Tamil Nadu Tourism" ,
                "tagline": "Enchanting Tamil Nadu" ,
                "desc": "\n Tamil Nadu- A land of cultural and religious heritage, offers every chance to its tourists and pilgrims to be enchanted with the vast plethora of history and beauty that it has. It is a blend of both- the modern and the ancient, which makes Tamil Nadu a beautiful destination to explore and experience our past cultural heritage with all the amenities of the present.\n\n Lying along the Bay of Bengal, Tamil Nadu has a glorious history that spans to a millennium and a present, that is paving a way for it in becoming one of the most promising states in the country. This state has seen the rise and fall of many dynasties such as the Cholas, the Cheras and the Pallavas. Each dynasty has enriched the place with its customs and traditions. Tamil Nadu sees a lot of tourists coming from all over the world to see the famous Meenakshi Temple, the tip of India - Kanyakumari or the beautiful hill station of Ooty. There is a great fascination to explore the ruins of the forts and palaces of the then great dynasties. The intricately carved structure of Mahabalipuram offers an insight into the architectural splendour of the Indian Civilization.\nRead More\n" ,
                "img": "https://www.holidify.com/images/bgImages/TAMIL-NADU.jpg"})
        arr.push({"title": "Tripura Tourism" ,
                "tagline": "Amazing Tripura" ,
                "desc": "\n Rich in gorgeous landscapes, crystalline waterfalls, awe-inspiring mountains, dense forests, and a generous sprinkling of history and tradition, Tripura is a popular tourist destination situated in North-East India. This land-locked state nestled at the foot of the Himalayan mountains has a long historical legacy behind it; Tripura was once home to the famous Manikya tribe, which resulted in the conception of a plethora of varied archaeological monuments and structures in the state, all of which attest to the rich cultural and traditional past of Tripura. The state exhibits a unique blend of traditional tribal culture with a little more modern Bengali culture, giving rise to a harmonious cultural ambience that you will not find anywhere else in the country. Tripura is more than just its breathtaking beauty; it is an illustration of a long and varied legacy of history and tradition, thus promising you a holiday you won?t forget anytime soon.\n\n Rich in art and culture, the land of nineteen tribes, Tripura is situated in the lush green hills and blessed with natural beauty and picturesque locations which attract tourists from all over the world. The religious festivals, colourful costumes, artistic cane and bamboo products, multi-linguistic people and delicious food, memorable sightseeing, adventurous trekking and lively shopping experience- There is nothing that Tripura lacks and will regenerate and rejuvenate your soul and spirit.\nRead More\n" ,
                "img": "https://www.holidify.com/images/bgImages/TRIPURA.jpg"})
        arr.push({"title": "Uttarakhand Tourism" ,
                "tagline": "The Land of Gods" ,
                "desc": "\n Land of untouched natural beauty and spirituality, Uttarakhand is a Himalayan state of North India, famously known as Devbhumi (or the Land of the Gods). Carved out from Uttar Pradesh, the state, formerly known as Uttaranchal, is a place that not only boasts of a scintillating view of the Himalayas but also exhibits a cultural ethos which speaks of a harmonic coexistence with nature.\n\n Uttarakhand is a popular pilgrimage site, as it is the originating spot of the Ganga and the Yamuna, two of the most sacred rivers for Hindus. Uttarakhand is home to the Char Dhams, the four most holy sites of pilgrimage revered by the Hindus - Gangotri, Yamunotri, Kedarnath, and Badrinath. Thousands of tourists visit Uttarakhand annually to pay homage to the Char Dhams.With oaks, birches, silver firs and rhododendrons adorning the steep mountain slopes, Uttarakhand offers you a glimpse into an untainted and idyllic world.\nRead More\n" ,
                "img": "https://www.holidify.com/images/bgImages/UTTARAKHAND.jpg"})
        arr.push({"title": "Uttar Pradesh Tourism" ,
                "tagline": "Amazing Heritage, Grand Experiences" ,
                "desc": "\n Home to one of the Seven Wonders of the World and flaunting exquisite arts like the handicrafts and jewellery Uttar Pradesh is a bountiful state and an utterly religious one. It is the home to some of the most beautiful monuments and cultural sights in India. The home to diverse religious people, this state boasts of the various cultural and religious fests. With massive royal influence in the fields of dance and music and arts, this state is home to one of the first classical dances of India, Kathak.\n\n The state is also known for its Nawabi style in food, can advertise fantastic street food like the samosa and kachori as well as the royal meaty feasts and kebabs. The land of Ram, Lord Krishna, the Buddha and the Taj Mahal- Uttar Pradesh, rich in diversity, transcends all boundaries of art and culture and brings together a lively mix of people from all around the nation.\nRead More\n" ,
                "img": "https://www.holidify.com/images/bgImages/UTTAR-PRADESH.jpg"})
        arr.push({"title": "Haryana Tourism" ,
                "tagline": "A Pioneer in Highway Tourism" ,
                "desc": "\n Haryana is a vibrant state that has managed to retain the best of both worlds- the ancient yet vibrant past and an exciting future to look forward to. It is a state that celebrates art and culture much like the rest of India celebrating its festivals, a panorama of vivid landscapes and exquisite archaeology.\u00a0Famous not just for its historical sites, its pleasant climate and its quaint landscapes, Haryana is also renowned for being a land of immense cultural diversity, a place often praised for its cordial and amicable ambience, and a state where modern buildings and edifices are as crucial as acres and acres of green fields, vibrant sunsets, and a rich culture that radiates through every nook and cranny of the state.\u00a0\n\n Often known as the 'Land of Milk and Butter', Haryana has, over time, stood witness to some of the most critical events in the course of Indian history, aptly giving it its title of being the land of lore, myth, and ancient history that still rings loud in the very air of the state. A state that is truly traditional in every way, Haryana is the home to some of the best handicraft and handloom carnivals. Flaunting an excellent variety of flora and fauna, the state hosts many bird species both migratory and residential. There are a lot of temples and lakes that are a sight to behold. The enthusiastic adventurer that finds himself in Haryana can pursue many activities like rock climbing, boating and hiking. One cannot go empty-handed from a place like Haryana that offers beautiful artistry in the form of Jutis and floral embroidery.\nRead More\n" ,
                "img": "https://www.holidify.com/images/bgImages/HARYANA.jpg"})
        arr.push({"title": "Himachal Pradesh Tourism" ,
                "tagline": "Land of Himalayas" ,
                "desc": "\n Himachal Pradesh is an Indian state located in the northern part of the country. Endowed with lofty Himalayan mountains, ancient religious sites and a cheerful culture,\u00a0Himachal Pradesh is home to\u00a0famous tourist destinations like Kullu, Manali, Chamba and Shimla.\n\n Himachal Pradesh is known as the state of apples all over India. It is also\u00a0known for\u00a0scenic\u00a0landscapes, culture, adventure sports and a variety of fairs, festivals and celebrations throughout the year. McLeod Ganj, the abode of the 14th Dalai Lama is worth visiting. Himachal Pradesh also has plenty of forts, palaces, and monasteries that are of utmost cultural and historical importance. Himachal Pradesh is located in the north of India bordering Jammu & Kashmir, Uttarakhand, Uttaranchal and Punjab and a boundary with Tibet.\u00a0\nRead More\n" ,
                "img": "https://www.holidify.com/images/bgImages/HIMACHAL-PRADESH.jpg"})
        arr.push({"title": "Chhattisgarh Tourism" ,
                "tagline": "Full of Surprises" ,
                "desc": "\n Chattisgarh, renowned for its scenic diversity and its cultural and traditional history, is slowly growing into one of India?s most popular holiday destinations. The oldest tribes of India dwell here, some of them for almost 10,000 years. A blend of culture, arts and religion of the local and tribal people, Chattisgarh exhibits the instance of ancient India. Still in its nascent stage though, Chhattisgarh is one of those off-the-beaten-track tourist spots in India that are slowly gaining more popularity through word-of-mouth. Home to plenty of gushing waterfalls, ancient temples and monuments, dense forests, a veritable sprinkling of flora and fauna, and a culture that is still reminiscent of the age-old history and traditions of the state, Chhattisgarh has everything you could be looking for in an ideal tourist spot where you can make memories that will last you a lifetime.\u00a0\u00a0\n\n Many of the caves and monuments present in Chattisgarh depict the sheer talent once possessed by the local architects and artisans. The lush green forests are idle sites for tourists to indulge in trekking and safaris and to absorb the ambience of various plant and animal species. The greenery and the waterfalls among the hilly regions of the state is a scene all admire. The Kailash cave located into the thick woods around Tiratgarh waterfalls is evidence of Chattisgarh's history.\u00a0\nRead More\n" ,
                "img": "https://www.holidify.com/images/bgImages/CHATTISGARH.jpg"})
    const [andhra, setAndhra] = useState(arr[0])
    const [assam, setAssam] = useState(arr[1])
    const [arunachal, setArunachal] = useState(arr[2])
    const [bihar, setBihar] = useState(arr[3])
    const [goa, setGoa] = useState(arr[4])
    const [gujarat, setGujarat] = useState(arr[5])
    const [jammu, setJammu] = useState(arr[6])
    const [jharkhand, setJharkhand] = useState(arr[7])
    const [bengal, setBengal] = useState(arr[8])
    const [karnataka, setKarnataka] = useState(arr[9])
    const [kerala, setKerala] = useState(arr[10])
    const [madhya_pradesh, setMadhya_pradesh] = useState(arr[11])
    const [maharashtra, setMaharashtra] = useState(arr[12])
    const [manipur, setManipur] = useState(arr[13])
    const [meghalaya, setMeghalaya] = useState(arr[14])
    const [mizoram, setMizoram] = useState(arr[15])
    const [nagaland, setNagaland] = useState(arr[16])
    const [orissa, setOrissa] = useState(arr[17])
    const [punjab, setPunjab] = useState(arr[18])
    const [rajasthan, setRajasthan] = useState(arr[19])
    const [sikkim, setSikkim] = useState(arr[20])
    const [tamil, setTamil] = useState(arr[21])
    const [tripura, setTripura] = useState(arr[22])
    const [uttarakhand, setUttarakhand] = useState(arr[23])
    const [uttar_pradesh, setUttar_pradesh] = useState(arr[24])
    const [haryana, setHaryana] = useState(arr[25])
    const [himachal, setHimachal] = useState(arr[26])
    const [chhattisgarh, setChhattisgarh] = useState(arr[27])
    const locationArray = {
        "Andhra Pradesh":andhra,
        "Assam":assam,
        "Arunachal Pradesh":arunachal,
        "Bihar":bihar,
        "Goa":goa,
        "Gujarat":gujarat,
        "Jammu and Kashmir": jammu,
        "Jharkhand": jharkhand,
        "West Bengal": bengal,
        "Karnataka": karnataka ,
        "Kerala": kerala ,
        "Madhya Pradesh":madhya_pradesh ,
        "Maharashtra":maharashtra ,
        "Manipur":manipur ,
        "Meghalaya":meghalaya ,
        "Mizoram":mizoram ,
        "Nagaland": nagaland ,
        "Orissa": orissa ,
        "Punjab": punjab ,
        "Rajasthan":rajasthan ,
        "Sikkim":sikkim ,
        "Tamil Nadu":tamil ,
        "Tripura":tripura ,
        "Uttarakhand":uttarakhand ,
        "Uttar Pradesh":uttar_pradesh ,
        "Haryana":haryana ,
        "Himachal Pradesh":himachal ,
        "Chhattisgarh":chhattisgarh
    }
    return {
        andhra,
        assam,
        arunachal,
        bihar,
        goa,
        gujarat,
        jammu,
        jharkhand,
        bengal,
        karnataka,
        kerala,
        madhya_pradesh,
        maharashtra,
        manipur,
        meghalaya,
        mizoram,
        nagaland,
        orissa,
        punjab,
        rajasthan,
        sikkim,
        tamil,
        tripura,
        uttarakhand,
        uttar_pradesh,
        haryana,
        himachal,
        chhattisgarh,
        locationArray
    }
}